# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210424_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_link_secret',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
