# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-01 19:25
# https://docs.djangoproject.com/en/1.11/howto/writing-migrations/#migrations-that-add-unique-fields
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def gen_uuud(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for row in UserProfile.objects.all():
        row.telegram_link_secret = uuid.uuid4()
        row.save(update_fields=['telegram_link_secret'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add telegram_link_secret_set_nulls'),
    ]

    operations = [
        migrations.RunPython(gen_uuud, reverse_code=migrations.RunPython.noop),
    ]
